### ISSUE TITLE
Question about "padding" in pool and conv function

### ISSUE THREAD

**Issue by kYroL01** [kratzert/finetune_alexnet_with_tensorflow#2]
Hi, this is not an issue but a question:

watching your code i wanna ask you why you pass `padding = VALID` when you call function [here](https://github.com/kratzert/finetune_alexnet_with_tensorflow/blob/fb83a1b8f2aa443a3914ca3b0d79d1a548de3234/alexnet.py#L47)

and in your [definition](https://github.com/kratzert/finetune_alexnet_with_tensorflow/blob/fb83a1b8f2aa443a3914ca3b0d79d1a548de3234/alexnet.py#L176) of that function you pass `padding = SAME`

Same thing about `conv`

Thanks for the huge work.
Hope you can solve my doubt

**Comment by kratzert** [comment]
Good question! This is more a kind of artifact in this code. I copied the layer helper functions from another project and didn't remove this default input setting.

But to be clear: The `padding = 'SAME'` in the definition of the layer functions is just used as default value if you aren't passing a padding argument when you call the function. Since I always explicitly write `padding = 'VALID'` when I call one of the layer functions, the default setting is ignored. 

For this repository it isn't the most beautiful way, better would be maybe to set `VALID` as input and don't pass any argument on function call or don't set any default. But yeah...as I said, this is more due to my lazy copy and paste ;)

**Comment by kYroL01** [comment]
@kratzert Thank you for the answer ;)
