### ISSUE TITLE
slice operation 

### ISSUE THREAD

**Issue by warmestwind** [kratzert/finetune_alexnet_with_tensorflow#22]
# RGB -> BGR
        img_bgr = img_centered[:, :, ::-1]

Hi bro, I am not familiar with python. Could you explain some about slice operation of list, as above from your code.
Thanks!

**Comment by kratzert** [comment]
Hey there,

what this slice operation does is switching the first and the last channel of a 3-d matrix (it's reversing the channels in the 3rd dimension). So we change an image from RGB ordering to BGR ordering, which is the expected input. For the rest, search around SO or similar, since there is a lot of information around for Pythons slicing.
