### ISSUE TITLE
Nan in summary histogram for: fc8/biases_0

### ISSUE THREAD

**Issue by yz21606948** [kratzert/finetune_alexnet_with_tensorflow#23]
I run fintune.py,but I get some error.Could someone plz tell me what's the problem and how to modify the code to solve it? Thank you

the error is flowing:
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: fc8/biases_0

**Comment by kratzert** [comment]
I just used the code myself today and it works without any problems for me.

It might help if you could specify a bit more what you are doing, what system you are running on and what version of Python, Tensorflow etc. Just by this one sentence its hard to help you

**Comment by hizagalilo** [comment]
Hi,
I have the same error. when i only choose fc8 The code works fine.
I thought to give the full Traceback.

2017-11-01 21:16:14.212079 Epoch number: 3
Traceback (most recent call last):
  File "D:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "D:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1306, in _run_fn
    status, run_metadata)
  File "D:\Python35\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "D:\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: fc6/weights_0
	 [[Node: fc6/weights_0 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](fc6/weights_0/tag, fc6/weights/read/_57)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python35\notebooks\finetune_alexnet_with_tensorflow2\finetune2.py", line 207, in <module>
    keep_prob: 1.})
  File "D:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "D:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    options, run_metadata)
  File "D:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: fc6/weights_0
	 [[Node: fc6/weights_0 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](fc6/weights_0/tag, fc6/weights/read/_57)]]

Caused by op 'fc6/weights_0', defined at:
  File "<string>", line 1, in <module>
  File "D:\Python35\lib\idlelib\run.py", line 124, in main
    ret = method(*args, **kwargs)
  File "D:\Python35\lib\idlelib\run.py", line 351, in runcode
    exec(code, self.locals)
  File "D:\Python35\notebooks\finetune_alexnet_with_tensorflow2\finetune2.py", line 142, in <module>
    tf.summary.histogram(var.name, var)
  File "D:\Python35\lib\site-packages\tensorflow\python\summary\summary.py", line 192, in histogram
    tag=tag, values=values, name=scope)
  File "D:\Python35\lib\site-packages\tensorflow\python\ops\gen_logging_ops.py", line 129, in _histogram_summary
    name=name)
  File "D:\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "D:\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "D:\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Nan in summary histogram for: fc6/weights_0
	 [[Node: fc6/weights_0 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](fc6/weights_0/tag, fc6/weights/read/_57)]]

**Comment by hizagalilo** [comment]
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> tf.VERSION
'1.3.0'

**Comment by hizagalilo** [comment]
I had the same error with all versions 1.x

**Comment by hizagalilo** [comment]
Windows 10

**Comment by kratzert** [comment]
The code runs for me and my data on my linux machine, as well as on my windows machine. When search for your error on google, it seems to be something related to the input data. What kind of image data are you using. Can you maybe test if this error occurs with some standard dataset like the cats and dogs example or imagenet validation set?

How many training samples and classes (as well as sample per class) are you using and whats your learning rate?

**Comment by yz21606948** [comment]
Hi,kratzert，my configuration is the same as above. Windows 7,Python 3.5.2,tensorflow1.2. The dataset is the cats and dogs example. I tried to change the line "loss=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=score,labels=y))" to
"loss=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=score,labels=tf.clip_by_value(y,1e-10,1.0)))".
My errors is solved,but causes a new error. The error is Nan in summary histogram for: fc6/weights_0.

**Comment by kratzert** [comment]
okay this seems strange. Gonna look into it this weekend hopefully with the same dataset. I use this code 2 days ago to finetune against another custom data set for my work and it worked without problems.. And you didn't change learning rate or any other parameter? And error occurs right from the beginning or later during training? Also did you take a look at tensorboard? How do the lose and accuracy graphs behaving as well as the gradients?

**Comment by kratzert** [comment]
Okay so I found time to try it out on my own and can reproduce the error for the cats and dogs dataset with the unchanged code of this repository. The error comes through the learning rate, which is to high for this data set. If you set the learning rate to 0.001 you won't have this error anymore and can finetune on the cats vs dogs dataset without problems.

Remember that the learning rate is a hyperparameter that needs to be adapted to each problem. It's maybe bad, that I chose cats vs dogs data as example in my blog post, but the code-as-is brings an error. But hey, now you have learned maybe something ;)

**Comment by hizagalilo** [comment]
Mine worked at 0.0009 learning rate

**Comment by yz21606948** [comment]
Hi,kratzert！ Thanks for your help.  I change the learning rate,it works.  I am a beginner for learning deeplearning. Your answer and your blog help me a lot . Thank you very much.




------------------ 原始邮件 ------------------
发件人: "Frederik Kratzert";<notifications@github.com>;
发送时间: 2017年11月4日(星期六) 晚上7:18
收件人: "kratzert/finetune_alexnet_with_tensorflow"<finetune_alexnet_with_tensorflow@noreply.github.com>;
抄送: "杨洲"<21606948@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [kratzert/finetune_alexnet_with_tensorflow] Nan in summaryhistogram for: fc8/biases_0 (#23)




Okay so I found time to try it out on my own and can reproduce the error for the cats and dogs dataset with the unchanged code of this repository. The error comes through the learning rate, which is to high for this data set. If you set the learning rate to 0.001 you won't have this error anymore and can finetune on the cats vs dogs dataset without problems.
 
Remember that the learning rate is a hyperparameter that needs to be adapted to each problem. It's maybe bad, that I chose cats vs dogs data as example in my blog post, but the code-as-is brings an error. But hey, now you have learned maybe something ;)

**Comment by pvij** [comment]
@kratzert I was facing a similar issue in my code. Thank you for solving it. I know the issue is closed but I have a question. It would be great if you could answer it. I am not able to understand how an increased learning rate results in the situation where a bias (or a weight) becomes NaN. I am using a bidirectional gru in my code which uses sigmoid and tanh functions whose derivatives don't go to infinity ever. And there's no division by zero in the weight or bias update rule. So how does the NaN pop up? Please correct me if I am wrong somewhere, I am still learning. Thank you.
