### ISSUE TITLE
How about using tf.estimator for training and prediction?

### ISSUE THREAD

**Issue by 17Skye17** [kratzert/finetune_alexnet_with_tensorflow#42]
Hello,Kratzert. Your blog and code are very nice,I am new to tensorflow and I learned a lot from them. 
Did you try the class: `tf.estimator`?I found that you defined modes for training and inference in file`datagenerator.py`, I refered to tensorflow tutorials and found tf.estimator can implement the same function.Why do you prefer not using this class?Maybe it has some disadvantages for summary operations?
 : )

**Comment by kratzert** [comment]
I don't use it because when I wrote this code the estimator class wasn't released. Since changing the code to the estimator class would require to me to rewrite the blog post, I'll stick with the old version. Might have some disadvantages but for the purpose of understanding what is happening, I think it's fine.
