### ISSUE TITLE
Image converting RGB to BGR

### ISSUE THREAD

**Issue by Auth0rM0rgan** [kratzert/finetune_alexnet_with_tensorflow#47]
Hello, 

Can you tell me the reason why you are converting RGB images to BGR in datagenerator.py? if I keep images as RGB what will happen? 

`img_bgr = img_centered[:, :, ::-1]`

**Comment by kratzert** [comment]
Because its AlexNet. You should maybe read the paper. AlexNet was trained with images in BGR format (Caffe default) and because you want to use the pretrained weights you have to convert your images also to BGR.
If you use RGB maybe the world will explode....(well what will happen, the convolutional feature dont make sense anymore because they see different data).
But since you train on these wrong features the fc top it might work but will be wrong in the essence of fine tuning AlexNet
