### ISSUE TITLE
Image Rescale Error

### ISSUE THREAD

**Issue by disdaining** [kratzert/finetune_alexnet_with_tensorflow#5]
I get the following error from datagenerator.py: 
`error: (-215) ssize.width > 0 && ssize.height > 0 in function resize`

`finetune_alexnet_with_tensorflow-master/datagenerator.py", line 150, in next_batch
    img = cv2.resize(img, (self.scale_size[0], self.scale_size[0]))
`

I debugged code as follows:

```
			img = cv2.imread(paths[i])
			print(img);
			if img is None:
				print (paths[i] + " : fail to read")
			else:
				print("Image is read");
			exit();
```

Error suggests that image is not read while in a separate program i verified that image is read: 

```
import numpy as np
import cv2

img = cv2.imread('images/ld2.png')
cv2.imwrite('messigray.png',img) 
```
Followed this [solution](http://stackoverflow.com/questions/31996367/opencv-resize-fails-on-large-image-with-error-215-ssize-area-0-in-funct) but couldn't work.

**Comment by kratzert** [comment]
Hmm hard to tell were the problem is. Since you say the there is no problem with the image in general, because you can load and resize in a separate script. Are you sure, that the path[i] points to the correct location (full path to the file e.g. /home/username/image_data/train/image1.png)? Unless you upload the image and provide the link here, I see no chance to help you, since it's definitely no problem in the code.

**Comment by disdaining** [comment]
Its simple but annoying. I have tried with both absolute and relative paths, doesn't seem to work. I tried another way to know the type of the image file using:
```
import imghdr
print(imghdr.what(paths[i]))
exit();
```
And surprisingly get:
`FileNotFoundError: [Errno 2] No such file or directory: "['images/147spaceship2.png']"
`
while manually doing same in python without running the script, it works. I have checked the path with double slashes as well. "['images//147spaceship2.png']"

Here is the [link](https://www.imageupload.co.uk/image/BG4z) to image.

**Comment by kratzert** [comment]
Well the error is pretty clear. Provide the full path an it should work. Relative path are always a bad idea if you are working with scripts, because it then depends from where you start the script (so which is the root folder for this session). I see no point in why full path shouldn't work. Are you working on windows or Linux? Because for the path you have to take care of the the separators ('/' or '\\'). The example I provided in the article where meant to be for Linux. For Windows the path should look something like:

C:\\Users\\image_data\\train\\image1.png

**Comment by disdaining** [comment]
Same error. Am using Linux. Doesn't accept any of the path. If i test with simpler version with 10 dog and cat images and then i insert mine then read in that version. I don't know why its not reading over here.

Here is a sample 1 row from trainData.txt:
/home/aaa/Downloads/finetune_alexnet_with_tensorflow/images/1asdsadasdasdsdsd1.png 0.68 0.37 0.3 0.46 0.4 0.37 0.17 0.25 0.31 0.13 0.61 0.3 0.26 0.26 0.55 0.34 0.27 0.38 0.59 0.02 0.51 0.41

**Comment by kratzert** [comment]
Well, if you use my datagenerator.py class you should also follow the rules of how to use them. Per line there should be only two arguments: image_path + class label and class label must be an integer. This shouldn't make much of a difference for this problem since the datagenerator.py only reads the first two arguments per line but will answer your future questions on the next problem you will encounter.

For the rest. Well I don't know what the problem is then. You must have missing one image, that you have in your text file and therefore have this input error. But this isn't a problem of this code repository nor anything I can solve for you.

**Comment by disdaining** [comment]
I know the data format which expect 2 cols and i have modified it to my requirements and doing the proper conversions as:
```

def read_class_list(self,class_list):
		"""
		Scan the image file and get the image paths and labels
		"""
		with open(class_list, 'r+') as f:
			subReader = csv.reader(f, delimiter=' ')
			subReader = list(subReader)
			self.images = []
			self.labels = []
			for row in subReader:
				self.images.append(str(row[0:1]))
				self.labels.append([float(s) for s in row[1:23]])				
			self.data_size = len(self.labels)
			print("Data size", self.data_size)

```
I have managed to solve the problem by using slicing to remove single quote and square brackets in the next_batch function:

```
for i in range(len(paths)):
			path = paths[i]
			path = path[2:-2]

```
Sample print of paths[0] prints: ['/home/aaa/Downloads/finetune_alexnet_with_tensorflow/images/cat1.png]', therefore i had to slice it and it becomes:
/home/aaa/Downloads/finetune_alexnet_with_tensorflow/images/cat1.png which is then readable in cv2.imread().

**Comment by disdaining** [comment]
Yes, i know format of the data and have done proper conversions. The solution to the current problem is  a single line:
`img = cv2.imread(str(*paths[i]))`
Converting paths[i] to str and using asterik to remove single quote and square brackets.
