### ISSUE TITLE
map() function in datagenerator.py has invalid argument

### ISSUE THREAD

**Issue by cbhanu** [kratzert/finetune_alexnet_with_tensorflow#54]
T.F. Version 1.8.0

Traceback (most recent call last):
  File "finetune.py", line 70, in <module>
    shuffle=True)
  File "/home/user/Desktop/finetune_alexnet_with_tensorflow/datagenerator.py", line 80, in __init__
    output_buffer_size=100*batch_size)
TypeError: map() got an unexpected keyword argument 'num_threads'

Any idea if this is a version error and recommendations to fix this ?

**Comment by cbhanu** [comment]
EDIT :: So this is the function definition in my version 

Signature: tf.data.Dataset.map(self, map_func, num_parallel_calls=None)
Docstring:
Maps `map_func` across this dataset.

Args:
  map_func: A function mapping a nested structure of tensors (having
    shapes and types defined by `self.output_shapes` and
   `self.output_types`) to another nested structure of tensors.
  num_parallel_calls: (Optional.) A `tf.int32` scalar `tf.Tensor`,
    representing the number elements to process in parallel. If not
    specified, elements will be processed sequentially.

Returns:
  Dataset: A `Dataset`.

How do I incorporate the logic of output_buffer_size in the above version then ?

**Comment by cbhanu** [comment]
Found it : Use data.prefetch(100*batch_size) afterwards instead of the output_buffer_size argument

**Comment by cbhanu** [comment]
But what is the purpose of this effectively ?Thanks

**Comment by kratzert** [comment]
As far as I know, TensorFlow switched the naming of the input arguments with some version. I didn't keep track because I switched to using PyTorch and am kind of unwilling to change code for every months TF release. If you have a fix that is working for the current TF 1.8 Version, feel free to make a pull request and I'll happily merge it.

The purpose of "num_calls", "num_parallel_calls", "prefetch" or how ever they name it now is to keep N samples prefetched and already preprocessed in the pipeline so that when ever e.g. the backward pass has finished, new data waits ready in memory. You just use the fact, that your CPU does nothing during forrward + backward pass, which runs on the GPU. So you can use the CPU for preprocessing
