### ISSUE TITLE
converting one hot lables for multiple float numbers

### ISSUE THREAD

**Issue by disdaining** [kratzert/finetune_alexnet_with_tensorflow#6]
How can i properly convert one hot labels for multiple float numbers? I have tried several methods but none work.

```
one_hot_labels = np.zeros((batch_size, self.n_classes))
		for i in range(len(labels)):
			for j in range(len(labels[i])):
			    one_hot_labels[i][labels[j]] = 1
		return images, one_hot_labels

```
Since i have multiple floating point numbers per image that's why i have to use another loop to iterate over its contents.

The error which i get is : 
`IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices`

Found this useful [library](https://rasbt.github.io/mlxtend/user_guide/preprocessing/one-hot_encoding/#api) but has floating point conversion errors.

Also tried manually converting labels list to numpy array and then re-evaluating, problem still exist.

**Comment by kratzert** [comment]
Correct me if I'm wrong but one-hot-encoding and float numbers don't make any sense. Do you know what one-hot-encoding is? Given a class label (as integer) you create a vector full of zeros with the same number of entries as you have classes, where for each sample you set the i-th entry to 1, with i being the class number? 

So tell me, how you want to translate a float number to a position in a vector? And again as for you last question, this has nothing to do with this code repository since it is related to classifying images into classes with AlexNet. I guess you should better post this question on stack overflow since you'll reach more people there.

**Comment by disdaining** [comment]
Sorry, this wasn't a relevant question. You are right about one hot encoding, just thought if its possible with floating numbers as well. This means, have to go one level above to the abstraction layer and define integer classes for floating numbers.
