### ISSUE TITLE
Would you be able to provide us with two .txt files?

### ISSUE THREAD

**Issue by gitskim** [kratzert/finetune_alexnet_with_tensorflow#65]

**Comment by kratzert** [comment]
How could I? The text files have to be specific to your training environment because they have to include the full path to the training images. Anyway the files have to look like this: In one line your have first the full path to a single image and then separated by an empty space the class number. So if you are on Linux it could look like

Example train.txt:
```
/home/gitskim/data/train/img0001.jpg 1
/home/gitskim/data/train/img0002.jpg 0
/home/gitskim/data/train/img0003.jpg 2
/home/gitskim/data/train/img0004.jpg 1
.
.
.

```
